feat: meilleurs affichages des listes emboîtées - fixes #41
empreinte-digitale/assistant-rgaa pull request #52
Opened 2022-11-09 10:33 UTC by nhattab

Lors du test du critère 9.3, s'il y a des listes emboîtées ce n'est pas très lisible. #41

![156608954-f7c1513f-56a1-4238-85cb-b6030c7e3a21](https://user-images.githubusercontent.com/117817104/200805037-644b446a-3fbc-4e0e-9531-088a811ab2a3.png)

Modifications:
1. Ajouts des espaces (margin & padding) entre les listes imbriquées.
2. Modification de la couleur des bordures pour chaque listes imbriquées. 

![Capture d’écran du 2022-11-09 10-57-17](https://user-images.githubusercontent.com/117817104/200800107-50474d14-017c-4a9b-9da6-6ec1465ff203.png)

2022-11-09 10:53 UTC, felixgirault requested changes
Je pense qu'il serait intéressant de reprendre l'idée de la discussion #41 : https://codepen.io/liszkowa/pen/gEgqdY

Ce qui me parait bon dedans c'est que les couleurs sont partagées entre les listes et items de même niveau, par exemple : 
```
ul rouge
  li rouge
  li rouge
    ul bleue
      li bleue
        ul verte
          li verte
…
```

Actuellement les styles sont génériques pour le contourage de n'importe quel type d'élément.
Je pense qu'il faudrait ajouter des cas spécifiques pour les listes, en faisant attention à ce que ça fonctionne toujours pour les autres éléments.

2022-11-09 10:53 UTC, felixgirault commented on fixtures/tests-thematique-9-structuration.html
> +							<ul>
Il faudrait que cet `<ul>` soit contenu dans un `<li>` pour que le HTML soit valide.

2022-11-09 10:53 UTC, felixgirault commented on fixtures/tests-thematique-9-structuration.html
> -		<ol>
Ici on pourrait laisser cette liste `ol`, pour avoir un exemple de listes `ol` *et* `ul`

2022-11-10 08:49 UTC, felixgirault requested changes

2022-11-10 08:49 UTC, felixgirault commented on css/helpers/components/rgaaExt-OutlineHelper.scss
> +	&[role='list'] {
C'est bien d'avoir séparé les deux types de listes, à la base je pensais faire un truc du genre pour mutualiser les styles :
```sass
ul.rgaaExt-OutlineHelper,
[role='list'].rgaaExt-OutlineHelper {
  /* … */

  & > li.rgaaExt-OutlineHelper,
  [role='listitem'] > li.rgaaExt-OutlineHelper {
    /* … */
  }
}
```
Mais je pense que ça aurait généré plus de styles que nécessaire.

Une autre option serait de faire un petit mixin Sass, qu'on puisse utiliser pour les deux types de listes, juste pour éviter de dupliquer le code.

2022-11-10 08:49 UTC, felixgirault commented on css/helpers/components/rgaaExt-OutlineHelper.scss
> +				}
Je pense qu'on devrait avoir la même structure que pour les listes classiques ici, ce sélecteur devrait contenir ceux d'en-dessous.

2022-11-10 08:49 UTC, felixgirault commented on css/helpers/components/rgaaExt-OutlineHelper.scss
> +			& [role='list'] {
Il faudrait qu'à chaque niveau on utilise bien le sélecteur d'enfant direct `>`, pour être sûrs que la chaîne de sélecteurs fonctionne comme prévu.

2022-11-10 08:49 UTC, felixgirault commented on css/helpers/components/rgaaExt-OutlineHelper.scss
> +	&[role='list'] {
A minima je sortirai ces styles pour les mettre au premier niveau, comme pour les listes classiques, pour être cohérent

2022-11-10 08:49 UTC, felixgirault commented on css/helpers/components/rgaaExt-OutlineHelper.scss
> +		&>[role='listitem'] {
Il faudrait qu'à chaque niveau on rappelle bien la classe `.rgaaExt-OutlineHelper`, comme pour les listes classiques : 
```scss
& > [role='listitem'].rgaaExt-OutlineHelper
```
sinon je pense que les styles ne fonctionneront pas bien à certains niveaux.

2022-11-10 10:25 UTC, nhattab reviewed
Création d'un mixin pour appliquer les même règles a tout les éléments listes (ul, li, role=list, role=lisitem) imbriquées pour éviter la répétition.   

![rgaa-list](https://user-images.githubusercontent.com/117817104/201065301-dd46f988-7aaa-406c-b408-4bbfe8c42c80.png)

![rgaa-non-list](https://user-images.githubusercontent.com/117817104/201065494-ebd6c916-ba81-48b9-a2cf-1fea8ed7790b.png)

2022-11-22 14:40 UTC, felixgirault approved these changes

2022-11-22 14:41 UTC, merged