Fix: validateur HTML W3C (HTML local) - fixes #47
empreinte-digitale/assistant-rgaa pull request #53
Opened 2022-11-14 09:10 UTC by nhattab

### Cette PR corrige le problème du validateur HTML des pages hors-ligne #47

Avant le correctif le validateur n'envoyé pas le code HTML au validateur W3C et la page reste bloquée sur chargement.

![validator-blocked-in-loading](https://user-images.githubusercontent.com/117817104/201617348-6171de00-c8cc-49d7-9b5b-d977f96eabdb.png)

Après le correctif le code source HTML est soumit au validateur W3C et on est redirigé vers la page qui affiche le rapport de scanne.

J'ai également remplacé l'input de type texte par un textarea pour garder la mise en forme du code source d'origine et avoir une meilleurs lisibilité.

Avec un input de type texte:
![html-validator-no-formatted](https://user-images.githubusercontent.com/117817104/201619793-63b6a109-5307-4dc3-8d2f-66954542cac5.png)

Avec un textarea:
![html-validator-formatted](https://user-images.githubusercontent.com/117817104/201618375-e3771a11-b005-47ec-8ea3-71be93312d33.png)

2022-11-14 09:32 UTC, felixgirault requested changes
J'ai mis quelques petites remarques mais dans l'ensemble c'est nickel, et bien vu d'avoir changé le type de champ pour le formatage :+1:

2022-11-14 09:32 UTC, felixgirault commented on pages/validateLocalPage.html
> +			<textarea name="fragment" value=""></textarea>
Pour être vraiment au propre, on pourrait séparer cette ligne dans un autre commit, puisqu'elle ne concerne pas le fix mais une amélioration en plus.

2022-11-14 09:32 UTC, felixgirault commented on src/common/api/validateLocalPage.js
> +export const validateLocalPage = async (url) => {
Ici je n'aurais pas utilisé `async`, même si on utilise des promesses on utilise pas `await` dans le corps de la fonction.
Ou alors il faudrait refactorer un peu (si tu veux le faire, dans l'idél il faudrait aussi le faire dans un autre commit).

2022-11-14 09:32 UTC, felixgirault commented on src/common/api/validateLocalPage.js
> +				const tabWindow = getWindowObject(tab.pendingUrl, {
Visiblement, `pendingUrl` n'est pas toujours défini, je pense qu'il faudrait garder un fallback comme `tab.pendingUrl || tab.url` (voir https://stackoverflow.com/a/60445157)

2022-11-14 09:32 UTC, felixgirault commented on src/common/api/validateLocalPage.js
> +				if (!tabWindow || typeof tabWindow?.validateSource !== 'function') {
Le test était buggé avant ou c'est dû aux autres changements plus haut ?

2022-11-14 09:52 UTC, nhattab commented on pages/validateLocalPage.html
> +			<textarea name="fragment" value=""></textarea>
Ok je met ça dans un autre commit

2022-11-14 10:34 UTC, felixgirault commented on src/common/api/validateLocalPage.js
> +				if (!tabWindow || typeof tabWindow?.validateSource !== 'function') {
ok nickel :+1:

2022-11-14 13:48 UTC, nhattab reviewed
Ignore ce commit car il n'apporte pas les changements attendues...

2022-11-14 13:49 UTC, nhattab reviewed
Commit à ignorer aussi les changements ne se sont pas appliquées

2023-03-29 13:46 UTC, felixgirault approved these changes

2023-03-29 14:24 UTC, merged