refactor: Refonte du scraper et la construction des références et instructions (critères et méthodologies).
empreinte-digitale/assistant-rgaa pull request #56
Opened 2022-11-18 13:50 UTC by nhattab

Cette PR apporte des changements au niveau du scraper et la construction des références et instructions (critères et méthodologies) RGAA v4.1 

Suite à la mise à disposition par [accessibilité.numerique.gouv.fr](https://github.com/DISIC/accessibilite.numerique.gouv.fr) des fichiers au format Json des critères et méthodologies, plus besoin de faire l'analyse syntaxique depuis le site pour récupérer les information et construire les fichiers utilisé par l’extension.

2022-11-18 14:59 UTC, felixgirault requested changes
Bien dans l'ensemble, ça m'a l'air de bien fonctionner :+1: 
Comme d'habitude j'ai beaucoup commenté mais c'est pour pousser la qualité un peu plus loin :)

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeInstructions42021.js
> +	return `<a  href="https://accessibilite.numerique.gouv.fr/methode/glossaire/${href}" target="_blank" title="${title ?? text}">${text}</a>`;
Nickel, c'est clean avec Marked :)

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeInstructions42021.js
> +	try {
Ici j'enlèverai peut-être le try {} catch qui englobe la fonction, puisqu'il ne sert qu'à renvoyer les erreurs qu'il catche.

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeInstructions42021.js
> +		console.log(`✅ Instructions list successfully generated.`);
Bonne idée de rajouter un peu de log :)
Dans l'idéal, on peut essayer de le sortir au plus haut niveau possible, histoire qu'il ne soit pas lié à l'implémentation de la fonctionnalité.
Ça aurait peut-être sa place dans la fonction au-dessus (`module.exports = (options) => (json) => {}`).
On pourrait retirer le try catch d'ici, et le remettre dans l'autre pour logger des messages en fonction

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeInstructions42021.js
> +	try {
(peut-être à ignorer si on suit mon commentaire suivant)

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeReference42021.js
> +	});
Le map est un peu étrange ici, il ressemble plutôt à un forEach, mais plus bas tu l'as bien fait.
```suggestion
	return rgaaJsonCriteria.topics.map((topic) => ({
		'id': `${topic.number}`,
		'title': `${topic.number}. ${topic.topic}`,
		'criteria': parseCriteria(topic.criteria, topic.number)
	}));
```

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeReference42021.js
> +	} catch (error) {
Comme sur l'autre scraper, on pourrait remonter le log plus haut

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeReference42021.js
> +	return wcag
Ici on pourrait passer par une seule regex pour récupérer le niveau, par exemple :
```js
function getWcagLevel(wcag) {
	// on veut un A ou plus, dans des parenthèses, en toute fin de chaîne
	const matches = wcag.match(/\((A+)\)$/);
	// si on a trouvé quelquechose, on retourne le niveau, sinon rien
	// (peut-être qu'il faudrait retourner "A" par défaut ?)
	return matches ? matches[1] : '';
}
```
(https://regex101.com/r/ogtnJj/1)

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeReference42021.js
> +		if (Object.hasOwnProperty.call(tests, key)) {
Ici je pense que cette condition sera toujours vraie car `key` est forcément une clé de `tests` (`for (const key in tests) {`)
On pourrait s'en passer.

2022-11-18 14:59 UTC, felixgirault commented on bin/scrapeReference42021.js
> +			];
Comme plus haut, j'ai l'impression qu'un `map` serait plus adapté ici 
```suggestion
return tests.map((test) => ({
	id: `${topicNumber}.${criteriumId}.${key}`, 
	title: marked(objectToList(tests[key]), { renderer })
}));
```

2022-11-18 14:59 UTC, felixgirault commented on bin/utils.js
> +		return textElement;
Bien vu de tester les paramètres :+1: 
Comme ça convertit des objets en listes, je retournerai plutôt `[]`, histoire d'avoir un type de retour uniforme.
Ou alors on peut lever une exception.

2022-11-18 14:59 UTC, felixgirault commented on bin/utils.js
> +function objectToList(textElement) {
Je pense que cette fonction est moins générique qu'elle le laisse entendre.
À lire le nom, je me dirais qu'elle prend un object pour en faire un array, du genre `(obj: Record<any, any>) => any[]`
En fait c'est là qu'on a la règle compliquée qui dit "la première ligne est un p mais les autres sont des li...", donc ça me parait très lié aux tests.
Je l'aurai bien déplacée dans le scraper, à côté du reste, et nommée plus clairement, par exemple `formatTest()`.

2022-11-18 14:59 UTC, felixgirault commented on bin/utils.js
> +		return textElement;
Par contre j'ai l'impression qu'on ne lui passe pas des objets mais des tableaux non ?

2022-11-18 14:59 UTC, felixgirault commented on bin/utils.js
> +			list += ` * ${elem}\n`;
Comme cette ligne n'est pas dans un `else`, je pense qu'on va toujours avoir la première ligne en doublon.

2022-11-18 14:59 UTC, felixgirault commented on bin/utils.js
> +	return list;
Ici on n'utilise pas key, je pense que le foreach n'est pas utile.
On pourrait encore transformer ça en un `map` plus léger, par exemple :
```suggestion
return textElement.map((elem, index) =>
	index === 0 
		? `${elem}\n`
		: ` * ${elem}\n`
)
```
Si on déplace cette fonction dans le scraper, il faudrait aussi renommer le paramètre de `textElement` à quelque chose de plus explicite, par exemple `instructions` ?

2022-11-21 08:21 UTC, nhattab commented on bin/utils.js
> +		return textElement;
J'ai cru aussi que ça allait être un tableaux amis en faite non, c'est un objet !

2022-11-21 08:24 UTC, nhattab commented on bin/utils.js
> +function objectToList(textElement) {
C'est un vrais que le nom n'est pas terrible, quand j'ai crée la fonction j'avais pas trouvé mieux, je vais prendre ton idée elle est plus adapté !

2022-11-21 09:13 UTC, felixgirault commented on bin/utils.js
> +			list += ` * ${elem}\n`;
Ça oui, mais pour la ligne 0 il va aussi l'ajouter en liste, puisqu'il n'y a pas de `break` ou `return` ?
En gros, au premier tour de boucle le code équivaut à 
```js
if (true) {
	list += `${elem}\n`;
}
list += ` * ${elem}\n`;
```
donc à :
```js
list += `${elem}\n`;
list += ` * ${elem}\n`;
```

2022-11-21 09:18 UTC, felixgirault commented on bin/scrapeReference42021.js
> +			];
Ah oui pardon c'est indexé par des chaînes ! En plus mon code était faux, on avait plus la variable `key`.
Dans ce cas on peut peut-être utiliser `Object.entries` ?
```js
return Object.entries(tests).map(([key, test]) => ({
	id: `${topicNumber}.${criteriumId}.${key}`, 
	title: marked(objectToList(tests[key]), { renderer })
}));
```

2022-11-21 09:29 UTC, felixgirault commented on bin/utils.js
> +		return textElement;
Ça m'étonne, on l'appelle comme ça `objectToList(tests[key])`, et `tests` est bien un objet mais `tests[key]` est censé être un tableau de chaînes non ?

2022-11-21 09:31 UTC, felixgirault reviewed
Désolé j'avais lu un peu vite certaines parties, j'espère que c'est plus clair maintenant :)

2022-11-21 09:40 UTC, nhattab commented on bin/utils.js
> +		return textElement;
Entonnement non ! quand je `console.log(typeof tests[key]` j'ai un type `object ` !

2022-11-21 17:14 UTC, ClementCousein reviewed
Quelques petits retours mais y a de bonnes choses c'est top :+1:

2022-11-21 17:14 UTC, ClementCousein commented on package.json
> +    "marked": "^4.2.3",
Le message de commit est pas en accord avec la modif dans le code au niveau de la version précédente.

2022-11-21 17:14 UTC, ClementCousein commented on bin/scrapeReference42021.js
> +		title ?? text
Nice l'usage de l'opérateur `??`. Par contre la doc au dessus laisse entendre que `text` peut être null mais pas `title`, du coup ça renverrait jamais l'opérande de droite ?

2022-11-21 17:14 UTC, ClementCousein commented on bin/scrapeReference42021.js
> +		});
Un peu bizarre l'utilisation de `Array.map` ici. 

`Array.map` va déjà te construire ton tableau, ici tu fais un peu comme si tu avais un `foreach`

Tu pourrais faire quelque chose comme ça :

```js
const themes = rgaaJsonCriteria.topics.map((topic) => (
	{
	        'id': `${topic.number}`,
	        'title': `${topic.number}. ${topic.topic}`,
	        'criteria': parseCriteria(topic.criteria, topic.number)
        }
 );
```

2022-11-21 17:14 UTC, ClementCousein commented on bin/scrapeReference42021.js
> +	return Object.entries(tests).map(([key, _]) => ({
Si tu itères que sur les clefs de ton objet tu peux utiliser directement `Object.keys`.

2022-11-21 17:14 UTC, ClementCousein commented on bin/scrapeReference42021.js
> +			list += ` * ${elem}\n`;
Si je comprends bien tu veux construire une chaine avec entre chaque élément le caractère ` * ` ?
Pareil que plus haut, `Array.map` peut te simplifier la vie ;) 
Je pense que tu pourrais faire plus simple en faisant 

```js
const list = textElements.map((element) => `${elem}\n`).join(' * ');
```

PS: J'ai l'impression que `textElement` pourrait s'appeler `textElements` ?

2022-11-22 08:20 UTC, nhattab commented on bin/scrapeReference42021.js
> +		title ?? text
Bien vue, erreur dans la JSdoc de ma part, c'est `title` qui peut être null

2022-11-22 08:56 UTC, nhattab commented on bin/scrapeReference42021.js
> +		});
Je crois que j'avais fait un `forEach` avant et puis j'ai changé en `map` sans refacto derrière.

2022-11-22 09:00 UTC, nhattab commented on bin/scrapeReference42021.js
> +			list += ` * ${elem}\n`;
Ici je dois construire un paragraphe et des listes en mardown, la première ligne est un p mais les autres sont des li...,

2022-11-22 09:40 UTC, felixgirault commented on bin/utils.js
> +		return textElement;
Ah oui ! C'est que le retour de `typeof` en JS est assez limité, il considère qu'un tableau est un objet au sens POO : il a des données et des méthodes (Techniquement c'est même [n'importe quoi qui ne soit pas un type primitif](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#description)).
```js
console.log(typeof []);
// 'object'
```
Si tu log vraiment la valeur `console.log(tests[key])`, je pense que tu verra bien un tableau (ou alors vraiment j'ai mal lu ^^)

2022-11-22 14:12 UTC, felixgirault commented on bin/scrapeReference42021.js
> +			list += ` * ${elem}\n`;
Comme vu ensemble on pourrait faire quelque chose comme ça :
```js
const paragraph = lines.shift();
const list = lines.map((line) => `* ${line}`);
return [paragraph, ...list].join('\n');
```
Ça permet de bien faire ressortir la règle métier

2022-11-22 14:35 UTC, felixgirault requested changes

2022-11-22 14:35 UTC, felixgirault commented on bin/scrapeReference42021.js
> +function withoutParagraph(html) {
On pourrait se passer de cette fonction, et autoriser les paragraphes dans les titres de critères.
Il faudrait juste modifier l'insertion dans le composant lié https://github.com/empreinte-digitale/assistant-rgaa/blob/refactor-rgaa-scraper/src/panel/components/Criterion.js#L79-L83 et vérifier si on n'utilise pas le titre ailleurs pour faire les modifications nécessaires

2022-11-22 14:35 UTC, felixgirault commented on bin/scrapeReference42021.js
> +	}));
Comme vu ensemble, la meilleure solution serait :
```js
return Object.entries(tests).map(([key, test]) => ({
	id: `${topicNumber}.${criteriumId}.${key}`,
	title: marked(formatTest(test), {renderer})
}));
```

2022-11-29 09:53 UTC, sbonaventure commented
De manière un peu générale, j'aimerais bien que ce scrapper écrase pas les fichiers du RGAA 4.1 (de 2021), car meme si ce n'est pas dit officiellement quelques intitulés de critères/tests ont été modifiés

Du coup, ce serait préférable que cela génère des fichiers 4.1-2022.json pour le référentiel, les tests et les helpers (pour l'instant le helpers 4.1-2022 serait "juste" une copie de celui de 2021)

2022-11-29 10:09 UTC, sbonaventure commented
Pareil, je ne sais pas trop ou mettre ça, mais dans les références, on désormais un ```<p>``` dans le ```title``` qu'on avait pas avant : https://github.com/empreinte-digitale/assistant-rgaa/compare/8917df3f5666845690c73d4892d911b674f26093..30206916784c0dff6ed7e412a27475312464293b#diff-cb03929a5776d153d48857a485f3bd01ef04c5f668fceb1434b6d5aacb03ceed

A supprimer je pense

2023-03-29 15:15 UTC, ClementCousein commented on bin/scrapeInstructions42021.js
> +	try {
à traiter

2023-03-29 15:21 UTC, ClementCousein commented
> @nhattab de manière un peu générale, j'aimerais bien que ce scrapper écrase pas les fichiers du RGAA 4.1 (de 2021), car meme si ce n'est pas dit officiellement quelques intitulés de critères/tests ont été modifiés
> 
> Du coup, ce serait préférable que cela génère des fichiers 4.1-2022.json pour le référentiel, les tests et les helpers (pour l'instant le helpers 4.1-2022 serait "juste" une copie de celui de 2021)

@nhattab Faudrait conserver la version 2021 du coup

2023-03-29 15:24 UTC, ClementCousein commented on bin/utils.js
> +		return textElement;
je vois plus cette fonction, je resolve la conversation

2023-03-30 07:12 UTC, sbonaventure commented
D'ailleurs, depuis on sait que cette nouvelle version du référentiel sera appellée 4.1.1 (https://github.com/DISIC/accessibilite.numerique.gouv.fr/pull/124)

il faudrait donc que les fichiers de sortie du scrapper s'appellent 4.1.1

2023-04-28 08:05 UTC, felixgirault requested changes

2023-04-28 08:05 UTC, felixgirault commented on manifest.json
> +		"data/references/4.1-2022.json"
On ajoute la v4.1-2022, mais les fichiers sont committés sous le nom 4.1-2023.json

2023-04-28 08:05 UTC, felixgirault commented on bin/utils.js
> +const jsonify = (data) => JSON.stringify(data, null, '\t');
J'ai l'impression qu'on a aucune modification sémantique dans ce fichier, seulement du formatage.
Je pense qu'on aurait pu l'enlever, ou éventuellement le committer séparément

2023-04-28 12:55 UTC, merged