feat: Affichage des cas particulier & notes technique #48
empreinte-digitale/assistant-rgaa pull request #58
Opened 2022-12-08 16:44 UTC by nhattab

Cette PR ajoute l'affichage par un système de `tab` les éléments suivant : 

- Les correspondances WCAG 2.1
- Les cas particuliers 
- Les notes techniques

Screeshot: 

![tabs-1](https://user-images.githubusercontent.com/117817104/206511942-aab54069-0638-40ac-a9de-d151223e7eca.png)
![tabs-2](https://user-images.githubusercontent.com/117817104/206512013-19758f0a-341f-4cdc-b441-cceb68d9a6b8.png)

2022-12-09 13:39 UTC, ClementCousein reviewed
Pas mal de petits retours, mais fondamentalement rien de bien méchant. 
Je vois que tu as bien capté comment marchait le `Array.map` par rapport à la MR précédente c'est top :+1:

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +const { marked } = require('marked');
Juste une petite remarque sur le formattage, faudrait enlever les espaces entre les accolades et `marked`. Prettier n'est pas passé sur ce fichier ?

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +const w3cTechniques = 'https://www.w3.org/WAI/WCAG21/Techniques/';
ça m'a l'air d'être du franglais ici, faudrait juste homogénéiser tout ça.

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +const w3cTechniques = 'https://www.w3.org/WAI/WCAG21/Techniques/';
Je ferai bien apparaître la notion d'URL également dans le nommage

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> + * Todo : finir de parser le texte WCAG pour build les liens
Normal qu'il reste un TODO ?

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +		if(hashUrl !==  null){
Pareil ici formattage,  je vais pas faire plus de remarque sur ce genre de trucs, un grand coup de prettier et on en parle plus ;)

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +const isLInk = new RegExp(/(https?:\/\/[^\s]+)/,  'g')
`isLink`, petit soucis de frappe

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +		const  alreadyLInk = href.match(isLInk)
`alreadyLink`, petit rechercher/remplacer pour corriger ça partout peut être

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +		return `<a  href="${alreadyLInk ? alreadyLInk[0] : link+href}" ${className ? `class="${className}"` : ''} target="${target}" title="${title ?? text + ' - nouvelle fenêtre'
Top le "nouvelle fenêtre" :+1:

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +}
Un peu bizarre cette fonction, tu redéfinies à chaque appel la méthode link de ton renderer qui est global et tu retournes ton renderer.
On pourra voir ensemble pour que tu m'expliques ce que tu voulais faire

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +function getParticularCases(particularCases) {
Je reverrais bien le nommage de cette fonction pour comprendre ce qu'elle fait vraiment.

J'ai l'impression qu'elle fait plus un `formatParticularCasesToMarkdown` qu'un `get`.

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +			"case": marked(pCase.ul.join('\n'), {renderer: markedLinkBuilder(accessNumeriqueLInk)})
Pas oblige de mettre le `case` entre quote ici vu que c'est un objet JS.

2022-12-09 13:39 UTC, ClementCousein commented on bin/scrapeReference42022.js
> +function getTechnicalNote(technicalNotes) {
idem ici

2022-12-09 13:39 UTC, ClementCousein commented on css/panel/components/ExternalsReferences.scss
> +			&:hover {
En général on double la plupart du temps le `hover` d'un `focus` pour les utilisateurs qui naviguent au clavier

2022-12-09 13:39 UTC, ClementCousein commented on css/panel/components/ParticularCases.scss
> +		&:after {
Normalement la vrai syntaxe pour les pseudo éléments c'est `::` pour différencier des pseudo classes.

Mais les navigateurs sont sympas ça marche quand même ;)

2022-12-09 13:39 UTC, ClementCousein commented on css/panel/components/ExternalsReferences.scss
> +	.Wcag-success-criteria {
Dans le projet on utilise une méthodologie BEM pour le nommage des classes. 

Avec une convention de nommage particulière => https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md

ça me parait bizarre qu'on ait ce genre de sélecteur. Pareil on pourra re boucler là dessus on a pas eu d'échanges encore là dessus.

2022-12-09 13:39 UTC, ClementCousein commented on css/panel/index.scss
> +@import './components//Tabs.scss';
Il y a un double `//` ici

2022-12-09 13:39 UTC, ClementCousein commented on src/panel/components/CriterionContainer.js
> +	const refLinksById = () => state.reference.criteria[id].references || [];
Ici j'aurais plus vu une fonction comme la ligne du dessus, un espèce de getter auquel tu passes un state, et un id du coup

2022-12-09 13:39 UTC, ClementCousein commented on src/panel/components/CriterionContainer.js
> +	const notes = () => state.reference.criteria[id].technicalNotes;
Pareil ici je verrais bien des fonctions comme plus haut, et utiliser un nommage qui fit ce que ça fait

2022-12-09 13:39 UTC, ClementCousein commented on src/panel/components/ExternalsReferences.js
> +					<abbr lang="en" title="Web content accessibility guidelines">
Nice :+1:

2022-12-09 13:39 UTC, ClementCousein commented on src/panel/components/ExternalsReferences.js
> +				<p>Critère(s) de succès: </p>
Peut être mettre les textes en dur dans le fichier de trads

2022-12-09 13:39 UTC, ClementCousein commented on src/panel/components/ParticularCases.js
> +								/>
Dans le projet tu as un composant `RichText` qui fait ce job , ça te permettra d'avoir un code plus concis et plus clair

2022-12-09 13:39 UTC, ClementCousein commented on src/panel/components/TechnicalNotes.js
> +}
Ce composant m'a l'air de faire exactement la même chose que `ParticularCases`.
Peut être moyen de factoriser ça ?

2022-12-09 15:38 UTC, nhattab commented on bin/scrapeReference42022.js
> + * Todo : finir de parser le texte WCAG pour build les liens
Non c'est pas normale ! bien vu,  c'est un oublie de ma part

2022-12-09 16:06 UTC, nhattab commented on bin/scrapeReference42022.js
> +function getParticularCases(particularCases) {
Initialement c’était juste un getter qui me retournait une `string`, mais je me suis rendu compte que parfois c'était un objet de liste avec une propriété `ul`

2022-12-09 16:16 UTC, nhattab commented on css/panel/components/ExternalsReferences.scss
> +			&:hover {
Ok j'ajoute ça

2022-12-09 16:21 UTC, nhattab commented on css/panel/components/ParticularCases.scss
> +		&:after {
ESlint qui me throw un warning quand je met les `::`  `Expected single colon pseudo-element notation`

2022-12-12 08:12 UTC, nhattab commented on bin/scrapeReference42022.js
> +const w3cTechniques = 'https://www.w3.org/WAI/WCAG21/Techniques/';
J'avoue le nommage est pas terrible... j'ai changé pour : 
 - `accessNumeriqueLInk` => `accessGouvUrl`
 - `w3cTechniques` => `w3cTechniquesUrl`
 - `w3cWcag21Fr` => `w3cWcag21FrUrl`

2022-12-12 09:18 UTC, ClementCousein commented on css/panel/components/ParticularCases.scss
> +		&:after {
:scream:

2022-12-12 09:47 UTC, nhattab commented on src/panel/components/ParticularCases.js
> +								/>
OK j'ai testé le composant `RichText` mais je vois qu'il a une class qui modifier pas mal le style de mes composants

2023-04-17 09:09 UTC, sbonaventure commented
🤔 je pense que le RGAA parle de "cas particuliers" plutôt que de "notes particulières"

2023-05-25 12:54 UTC, felixgirault requested changes

2023-05-25 12:54 UTC, felixgirault commented on bin/scrapeReference42023.js
> +					'technics': marked(
Le terme plus approprié est `techniques` en anglais, par exemple https://www.w3.org/WAI/WCAG21/Techniques/

2023-05-25 12:54 UTC, felixgirault commented on bin/scrapeReference42023.js
> +const wcagCategories = {
Ces catégories sont affichées dans l'interface ?
Je pense qu'il faudrait les traduire si c'est le cas

2023-05-25 12:54 UTC, felixgirault commented on bin/scrapeReference42023.js
> +#!/usr/bin/env nodew3cTechniquesLink
Ici le hashbang devrait rester `#!/usr/bin/env node` pour que le fichier soit exécutable avec node

2023-05-25 13:32 UTC, nhattab commented on bin/scrapeReference42023.js
> +const wcagCategories = {
Non, elles ne sont pas affichées dans l'interface, juste pour build mes liens

2023-05-25 13:39 UTC, nhattab commented on bin/scrapeReference42023.js
> +function markedLinkBuilder(link, className = null, target = '_blank') {
J'ai changé la logique, car le besoin a évolué avec le parsing des cas particulier et les notes techniques

2023-05-25 15:27 UTC, nhattab reviewed
C'est plus cohérent ;)

2023-05-25 15:36 UTC, nhattab reviewed
Ça me parait bien dans l'ensemble  👌

2023-05-25 16:14 UTC, felixgirault commented
J'ai refait une petite passe de styles pour avoir quelque chose de plus doux, et plus cohérent avec le reste de l'application (https://github.com/empreinte-digitale/assistant-rgaa/pull/58/commits/28e5580351a7029144fd56be7bae4d8066d09857)
![Capture d'écran 2023-05-25 18:04:35](https://github.com/empreinte-digitale/assistant-rgaa/assets/1544510/0eef4564-826b-4abf-85ac-dbcf2a8b70f5)
![Capture d'écran 2023-05-25 18:05:37](https://github.com/empreinte-digitale/assistant-rgaa/assets/1544510/6f43f01d-ba92-4215-95ef-51859160e0e1)

2023-06-14 09:06 UTC, felixgirault approved these changes

2023-06-15 07:42 UTC, merged